### ISSUE TITLE
Error  '(#100) Missing parameter(s): customer_file_source' when creating custom audience

### ISSUE THREAD

**Issue by adarmanto** [facebook/facebook-php-business-sdk#457]
Hello,

I followed this sample code to create a custom audience https://github.com/facebook/facebook-php-business-sdk/blob/master/examples/custom_audiences.php, it was working fine before. But recently I got this error below, I have updated the sdk to newer version (v3.0.4) also remain same issue.

```
exception 'FacebookAds\Http\Exception\AuthorizationException' with message '(#100) Missing parameter(s): customer_file_source' in /var/www/vhosts/xxx/vendor/facebook/php-business-sdk/src/FacebookAds/Http/Exception/RequestException.php:144
Stack trace:
#0 /var/www/vhosts/xxx/vendor/facebook/php-business-sdk/src/FacebookAds/Http/Client.php(215): FacebookAds\Http\Exception\RequestException::create(Object(FacebookAds\Http\Response))
#1 /var/www/vhosts/xxx/vendor/facebook/php-business-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
#2 /var/www/vhosts/xxx/vendor/facebook/php-business-sdk/src/FacebookAds/Api.php(162): FacebookAds\Http\Request->execute()
#3 /var/www/vhosts/xxx/vendor/facebook/php-business-sdk/src/FacebookAds/Api.php(204): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request))
#4 /var/www/vhosts/xxx/vendor/facebook/php-business-sdk/src/FacebookAds/Object/AbstractCrudObject.php(241): FacebookAds\Api->call('/act_38834xxx...', 'POST', Array)
#5 /var/www/vhosts/xxx/export/fb-audience-cron.php(164): FacebookAds\Object\AbstractCrudObject->create()
```
Any suggestion to solve this issue?

**Comment by adarmanto** [comment]
Opps sorry, it was new changes in API https://developers.facebook.com/ads/blog/post/2018/06/13/sharing-custom-audiences/

By adding new required param `customer_file_source` solve this issue.
